version: "3"

services:
  pageplug6:
    image: index.docker.io/cloudtogouser/pageplug-ce:v1.9.37
    container_name: pageplug6
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    environment:
      - TZ=Asia/Shanghai
      - APPSMITH_MONGODB_URI=mongodb://mongodb:27017/appsmith
      - APPSMITH_ENCRYPTION_PASSWORD=appsmith
      - APPSMITH_ENCRYPTION_SALT=appsmith
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.6
    container_name: mongodb
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=appsmith
    restart: unless-stopped
